
from Spacecraft.Spacecraft import Spacecraft
from Dynamics.SimTime import SimTime
from initial_config import InitialConfig
from Dynamics.SpacecraftOrbit.MainOrbit import MainOrbit
from Dynamics.CelestialBody.Ephemeris import Ephemeris
from Dynamics.SpacecraftAttitude.Attitude import Attitude
from Environments.Environment import Environment
from Disturbance.Disturbances import Disturbances

import numpy as np
import pandas as pd
import datetime

twopi   = 2.0 * np.pi
deg2rad = np.pi / 180.0
rad2deg = 1 / deg2rad


class MainSimulation(InitialConfig, MainOrbit, Attitude, SimTime, Environment, Ephemeris, Disturbances):
    def __init__(self):

        InitialConfig.__init__(self)

        self.main_spacecraft  = Spacecraft(self.spacecraft_properties, None)

        SimTime.__init__(self, self.time_properties)
        Attitude.__init__(self, self.main_spacecraft.attitude_dynamics,  self.attitudestep, self.attitude_update_flag)
        MainOrbit.__init__(self, self.orbit_properties)
        Ephemeris.__init__(self, self.wgs)
        Environment.__init__(self, self.radiusearthkm)
        Disturbances.__init__(self)

        self.current_alt = 0
        self.current_lat = 0
        self.current_long = 0

        # Auxiliary variables
        date = datetime.datetime.now()
        self.filename = date.strftime('%Y-%m-%d %H-%M-%S')

    def run_simulation(self):
        self.set_propagator()
        # Loop
        self.reset_countTime()
        while self.maincountTime <= self.endsimTime:

            # current time
            array_time, str_time = self.get_array_time()

            # current orbit position, velocity
            if self.orbit_update_flag:
                self.update_orbit(array_time)
                self.getSideral(self.current_jd)
                self.current_lat, self.current_long, self.current_alt = self.orbit_propagate.TransECItoGeo(
                    self.current_sideral)
                self.orbit_update_flag = False

            # current Attitude
            self.update_attitude(self.maincountTime)

            # current Environment and disturbances
            self.update_environment(self.current_decyaer,
                                    self.current_sideral,
                                    self.current_lat,
                                    self.current_long,
                                    self.current_alt,
                                    self.current_quaternion_i2b)

            self.update_disturbances()
            # Add the force and torque generated by the disturbance for the next dynamics propagation
            #self.add_ext_force_b()
            self.add_ext_torque_b(self.get_disturbance_torque())

            # Add the force and torque generated by the satellite for the next dynamics propagation
            #self.add_int_force(self.main_spacecraft.generate_force_b(inputs_parameters))
            #self.add_int_torque(self.main_spacecraft.generate_torque_b(inputs_parameters))

            if self.log_flag:
                self.progressionsimTime()
                self.main_spacecraft.update_spacecraft_dynamics(self.current_position,
                                                                self.current_velocity,
                                                                self.current_quaternion_i2b(),
                                                                self.current_omega_b,
                                                                self.h_total_norm,
                                                                self.current_lat,
                                                                self.current_long,
                                                                self.current_alt)

                self.main_spacecraft.update_spacecraft_state(str_time, self.maincountTime)
                self.main_spacecraft.update_control_history()
                self.gst_Update()
                self.log_flag = False

            # update time
            self.updateSimtime()

        # Data report to create dictionary
        self.main_spacecraft.create_data()

        # Save Dataframe pandas in csv file
        self.save_data()
        print('Finished')

    def save_data(self):
        master_data = {**self.main_spacecraft.master_data_satellite, **self.historical_gst}
        database = pd.DataFrame(master_data, columns=master_data.keys())
        database.to_csv("./Data/logs/"+self.filename+".csv", index=False, header=True)
        print("Data created")

